USE TitanicDB
GO

ALTER TABLE dbo.T ADD
CONSTRAINT PK_T PRIMARY KEY (TicketId), 
CONSTRAINT UK_T UNIQUE (Passenger)
GO

ALTER TABLE dbo.S ADD
CONSTRAINT PK_S PRIMARY KEY (PassengerId)
GO

ALTER TABLE dbo.P ADD
CONSTRAINT PK_P PRIMARY KEY (Passenger)
GO

ALTER TABLE dbo.PTS ADD
CONSTRAINT PK_PTS PRIMARY KEY (PassengerId, Passenger, TicketID),
CONSTRAINT FK_PTS_P FOREIGN KEY (Passenger) REFERENCES dbo.P (Passenger),
CONSTRAINT FK_PTS_T FOREIGN KEY (TicketId) REFERENCES dbo.T (TicketId),
CONSTRAINT FK_PTS_S FOREIGN KEY (PassengerId) REFERENCES dbo.S (PassengerId)
GO

ALTER TABLE dbo.T ADD
CONSTRAINT Ticket_chk CHECK (TicketId >= 0),
CONSTRAINT Fare_chk CHECK (Fare >= 0),
CONSTRAINT Num_chk CHECK (Persons BETWEEN 1 AND 10),
CONSTRAINT Class_chk CHECK (Class BETWEEN 1 AND 3),
CONSTRAINT Embarked_chk CHECK (Embarked='S' OR Embarked='C' OR Embarked='Q')
GO

ALTER TABLE dbo.S ADD
CONSTRAINT PassengerId_chk CHECK (PassengerId BETWEEN 1 AND 1000)
GO

ALTER TABLE dbo.P ADD
CONSTRAINT Sex_chk CHECK (Sex='male' OR Sex='Female') 
GO
